extends RefCounted
class_name EggSprites

## Which egg SPRITE stands for each cosmetic variant.
##
## Owner 2026-09-08: *"It would be cool if we could somehow have like a dictionary where you could
## tell what type of variant you are going to get by the artwork of the egg."* This is that
## dictionary. An egg's art tells you what you are going to hatch before you hatch it.
##
## GENERATED by `tools/bake_egg_variants.py`. Do not hand-edit a row - a hand-edited row is a
## second source of truth, and the next regeneration silently discards it.
##
## Every egg in `pet-egg-pack` is opened and its dominant body colour measured from the actual
## PIXELS, then matched to the nearest variant colour. Filenames are deliberately NOT trusted:
## they carry colour WORDS ("red-blue"), and a red-blue egg turns out to be a blended purple, so
## the name describes the inputs rather than what the player sees.
##
## 2026-09-11 - EVERY VARIANT NOW HAS ITS OWN EGG. 119 variants, 119 distinct sprites, zero
## collisions.
##
## The previous generator was greedy nearest-colour with a "spread the picks out" penalty tuned
## to 2000, which gave 95 distinct eggs and 24 variants sharing one with a near-identical
## neighbour. That was accepted at the time, then surfaced as 20 warnings from
## `verify_dungeon_art.gd`: Zebra and Duality drawing the same egg, Framed / Misty / Corona all
## drawing another. A player could not tell those apart before hatching - which is the one thing
## this table exists to make possible.
##
## A penalty cannot guarantee uniqueness, it can only discourage collisions. With 119 variants
## and 626 usable eggs a one-to-one assignment plainly exists, so it is solved as an ASSIGNMENT:
## take the globally cheapest (variant, egg) pair still available, repeatedly. Greedy over the
## whole matrix rather than per-variant, which makes collisions impossible by construction
## instead of merely unlikely.
##
## THREE THINGS THE GENERATOR MUST KEEP DOING, each a mistake already made:
##   * Near-black pixels count as OUTLINE only when they are a minority. Discarding them
##     unconditionally means a black egg can never match a black variant, and sent Obsidian,
##     Eclipse, Void, Barcode and Jailbird to pale eggs.
##   * Untextured TEMPLATES are excluded (fewer than 20 distinct colours - the same threshold
##     `verify_dungeon_art.gd` fails the build on). The first clean run of the new matcher handed
##     `0624-egg-base.png` to Ivory and the gate rejected it.
##   * PATTERN is still lost: striped / split_v / checker cannot survive being a single sprite.
##     Accepted by the owner, unchanged.
##
## HONEST LIMIT: distinct does not mean obviously distinct. Several variants are near-identical
## COLOURS by definition (Outlined / Speckled / Starry / Misty are all pale), so their eggs are
## different files that still read as similar at a glance. Telling those apart needs new art or
## a recolour pass, not a better matcher.

const SPRITE_BY_VARIANT := {
	"Crimson": "res://client/sprites/pet-egg-pack/eggs/named/0615-ruby.png",
	"Azure": "res://client/sprites/pet-egg-pack/eggs/named/0612-photon-frost.png",
	"Verdant": "res://client/sprites/pet-egg-pack/eggs/named/0449-forest-gold.png",
	"Silver": "res://client/sprites/pet-egg-pack/eggs/colorways/0371-periwinkle-cream.png",
	"Amber": "res://client/sprites/pet-egg-pack/eggs/colorways/0396-yellow-gold.png",
	"Obsidian": "res://client/sprites/pet-egg-pack/eggs/named/0447-dark-forest.png",
	"Scarlet": "res://client/sprites/pet-egg-pack/eggs/named/0502-martian-dust.png",
	"Cobalt": "res://client/sprites/pet-egg-pack/eggs/named/0444-cobalt-rose.png",
	"Golden": "res://client/sprites/pet-egg-pack/eggs/colorways/0402-yellow-gold.png",
	"Shadow": "res://client/sprites/pet-egg-pack/eggs/colorways/0012-black.png",
	"Violet": "res://client/sprites/pet-egg-pack/eggs/named/0584-amethyst.png",
	"Coral": "res://client/sprites/pet-egg-pack/eggs/colorways/0189-red-orange.png",
	"Teal": "res://client/sprites/pet-egg-pack/eggs/named/0451-lagoon-lime.png",
	"Rose": "res://client/sprites/pet-egg-pack/eggs/named/0517-ruby.png",
	"Lime": "res://client/sprites/pet-egg-pack/eggs/named/0603-jungle-static.png",
	"Copper": "res://client/sprites/pet-egg-pack/eggs/named/0619-spain.png",
	"Frost": "res://client/sprites/pet-egg-pack/eggs/colorways/0287-white-cyan.png",
	"Infernal": "res://client/sprites/pet-egg-pack/eggs/colorways/0180-red-gold.png",
	"Toxic": "res://client/sprites/pet-egg-pack/eggs/colorways/0399-yellow-lime-green.png",
	"Amethyst": "res://client/sprites/pet-egg-pack/eggs/named/0470-amethyst-veil.png",
	"Midnight": "res://client/sprites/pet-egg-pack/eggs/named/0455-night-glow.png",
	"Ivory": "res://client/sprites/pet-egg-pack/eggs/colorways/0291-white-cream.png",
	"Rust": "res://client/sprites/pet-egg-pack/eggs/named/0489-ember-gilt-matte.png",
	"Mint": "res://client/sprites/pet-egg-pack/eggs/colorways/0195-green-white.png",
	"Sunset": "res://client/sprites/pet-egg-pack/eggs/colorways/0428-orange-gold.png",
	"Ocean": "res://client/sprites/pet-egg-pack/eggs/named/0568-quasar-ice.png",
	"Forest": "res://client/sprites/pet-egg-pack/eggs/colorways/0061-green-black.png",
	"Dusk": "res://client/sprites/pet-egg-pack/eggs/named/0581-void-orchid.png",
	"Ember": "res://client/sprites/pet-egg-pack/eggs/named/0548-garnet.png",
	"Arctic": "res://client/sprites/pet-egg-pack/eggs/colorways/0282-white-silver.png",
	"Volcanic": "res://client/sprites/pet-egg-pack/eggs/named/0597-garnet.png",
	"Twilight": "res://client/sprites/pet-egg-pack/eggs/named/0528-void-orchid.png",
	"Dawn": "res://client/sprites/pet-egg-pack/eggs/colorways/0394-yellow-orange.png",
	"Depths": "res://client/sprites/pet-egg-pack/eggs/named/0614-quasar-ice.png",
	"Bloom": "res://client/sprites/pet-egg-pack/eggs/named/0613-plasma-lime.png",
	"Rising": "res://client/sprites/pet-egg-pack/eggs/named/0617-solar-flare.png",
	"Core": "res://client/sprites/pet-egg-pack/eggs/named/0606-martian-dust.png",
	"Heart": "res://client/sprites/pet-egg-pack/eggs/named/0547-event-horizon.png",
	"Soul": "res://client/sprites/pet-egg-pack/eggs/named/0514-quasar-ice.png",
	"Nexus": "res://client/sprites/pet-egg-pack/eggs/colorways/0024-lime-green.png",
	"Beacon": "res://client/sprites/pet-egg-pack/eggs/named/0525-supernova-gold.png",
	"Tiger": "res://client/sprites/pet-egg-pack/eggs/named/0621-supernova-gold.png",
	"Candy": "res://client/sprites/pet-egg-pack/eggs/colorways/0229-white-cream.png",
	"Electric": "res://client/sprites/pet-egg-pack/eggs/colorways/0157-lime-green-gold.png",
	"Aquatic": "res://client/sprites/pet-egg-pack/eggs/named/0557-lagoon-glass-matte.png",
	"Regal": "res://client/sprites/pet-egg-pack/eggs/colorways/0331-pink-brown.png",
	"Haunted": "res://client/sprites/pet-egg-pack/eggs/named/0466-violet-fire.png",
	"Outlined": "res://client/sprites/pet-egg-pack/eggs/colorways/0038-blue-yellow.png",
	"Glowing": "res://client/sprites/pet-egg-pack/eggs/named/0600-ion-storm.png",
	"Burning": "res://client/sprites/pet-egg-pack/eggs/named/0572-solar-flare.png",
	"Frozen": "res://client/sprites/pet-egg-pack/eggs/colorways/0247-cyan-cream.png",
	"Toxic Glow": "res://client/sprites/pet-egg-pack/eggs/named/0607-meadow-ceramic-matte.png",
	"Slash": "res://client/sprites/pet-egg-pack/eggs/colorways/0271-orange-gold.png",
	"Lightning": "res://client/sprites/pet-egg-pack/eggs/colorways/0029-gold.png",
	"Rift": "res://client/sprites/pet-egg-pack/eggs/colorways/0388-blue-periwinkle.png",
	"Shattered": "res://client/sprites/pet-egg-pack/eggs/colorways/0044-blue-green-alt.png",
	"Ascendant": "res://client/sprites/pet-egg-pack/eggs/colorways/0257-yellow-cream.png",
	"Phoenix": "res://client/sprites/pet-egg-pack/eggs/colorways/0264-red-gold.png",
	"Comet": "res://client/sprites/pet-egg-pack/eggs/colorways/0186-blue-cream.png",
	"Crescent": "res://client/sprites/pet-egg-pack/eggs/named/0531-amethyst.png",
	"Split": "res://client/sprites/pet-egg-pack/eggs/named/0596-event-horizon.png",
	"Duality": "res://client/sprites/pet-egg-pack/eggs/colorways/0041-blue-gold.png",
	"Twilit": "res://client/sprites/pet-egg-pack/eggs/colorways/0381-blue-grey.png",
	"Balanced": "res://client/sprites/pet-egg-pack/eggs/named/0498-japan.png",
	"Chimeric": "res://client/sprites/pet-egg-pack/eggs/colorways/0166-gold-brown.png",
	"Mosaic": "res://client/sprites/pet-egg-pack/eggs/colorways/0295-gold-green-alt.png",
	"Harlequin": "res://client/sprites/pet-egg-pack/eggs/colorways/0232-red-gold.png",
	"Aura": "res://client/sprites/pet-egg-pack/eggs/colorways/0014-red-gold.png",
	"Corona": "res://client/sprites/pet-egg-pack/eggs/colorways/0398-yellow-pink.png",
	"Eclipse": "res://client/sprites/pet-egg-pack/eggs/colorways/0127-gold-brown.png",
	"Barcode": "res://client/sprites/pet-egg-pack/eggs/colorways/0077-purple-lime-green.png",
	"Zebra": "res://client/sprites/pet-egg-pack/eggs/colorways/0231-pink-teal-cream.png",
	"Neon Bars": "res://client/sprites/pet-egg-pack/eggs/named/0626-pattern-ribbon-wave.png",
	"Jailbird": "res://client/sprites/pet-egg-pack/eggs/colorways/0032-brown.png",
	"Layered": "res://client/sprites/pet-egg-pack/eggs/named/0594-ember-gilt-matte.png",
	"Stratified": "res://client/sprites/pet-egg-pack/eggs/colorways/0433-periwinkle-teal.png",
	"Sediment": "res://client/sprites/pet-egg-pack/eggs/colorways/0020-grey.png",
	"Framed": "res://client/sprites/pet-egg-pack/eggs/colorways/0311-silver-tan.png",
	"Gilded": "res://client/sprites/pet-egg-pack/eggs/named/0576-supernova-gold.png",
	"Corrupted": "res://client/sprites/pet-egg-pack/eggs/named/0530-acid-cabaret.png",
	"Marked": "res://client/sprites/pet-egg-pack/eggs/colorways/0267-orange-pink.png",
	"Hex": "res://client/sprites/pet-egg-pack/eggs/colorways/0071-purple-black.png",
	"Branded": "res://client/sprites/pet-egg-pack/eggs/named/0520-solar-flare.png",
	"Tidal": "res://client/sprites/pet-egg-pack/eggs/named/0501-lagoon-glass-matte.png",
	"Ripple": "res://client/sprites/pet-egg-pack/eggs/colorways/0352-burgundy-periwinkle.png",
	"Current": "res://client/sprites/pet-egg-pack/eggs/named/0495-ion-storm.png",
	"Mirage": "res://client/sprites/pet-egg-pack/eggs/colorways/0191-yellow-cream-variant-2.png",
	"Speckled": "res://client/sprites/pet-egg-pack/eggs/colorways/0109-white-grey.png",
	"Starry": "res://client/sprites/pet-egg-pack/eggs/colorways/0137-silver-periwinkle.png",
	"Freckled": "res://client/sprites/pet-egg-pack/eggs/named/0545-ember-gilt-matte.png",
	"Glittering": "res://client/sprites/pet-egg-pack/eggs/colorways/0028-red-gold.png",
	"Spotted": "res://client/sprites/pet-egg-pack/eggs/named/0574-spain.png",
	"Ringed": "res://client/sprites/pet-egg-pack/eggs/named/0465-twilight.png",
	"Orbital": "res://client/sprites/pet-egg-pack/eggs/named/0605-lagoon-glass-matte.png",
	"Halo": "res://client/sprites/pet-egg-pack/eggs/colorways/0187-yellow-white.png",
	"Misty": "res://client/sprites/pet-egg-pack/eggs/colorways/0238-silver-cream.png",
	"Smoky": "res://client/sprites/pet-egg-pack/eggs/colorways/0105-black-brown.png",
	"Dreamlike": "res://client/sprites/pet-egg-pack/eggs/colorways/0284-white-pink.png",
	"Fading": "res://client/sprites/pet-egg-pack/eggs/named/0616-sapphire.png",
	"Shiny": "res://client/sprites/pet-egg-pack/eggs/colorways/0228-white-cream-variant-2.png",
	"Radiant": "res://client/sprites/pet-egg-pack/eggs/colorways/0395-yellow-white.png",
	"Blessed": "res://client/sprites/pet-egg-pack/eggs/colorways/0303-gold-cream.png",
	"Starfall": "res://client/sprites/pet-egg-pack/eggs/colorways/0093-orange-brown.png",
	"Spectral": "res://client/sprites/pet-egg-pack/eggs/colorways/0332-pink-periwinkle.png",
	"Ethereal": "res://client/sprites/pet-egg-pack/eggs/colorways/0251-periwinkle-cream.png",
	"Celestial": "res://client/sprites/pet-egg-pack/eggs/colorways/0192-yellow-cream.png",
	"Bifrost": "res://client/sprites/pet-egg-pack/eggs/colorways/0212-black-white-variant-2.png",
	"Prismatic": "res://client/sprites/pet-egg-pack/eggs/named/0487-comet-tail.png",
	"Void": "res://client/sprites/pet-egg-pack/eggs/colorways/0102-black-burgundy.png",
	"Cosmic": "res://client/sprites/pet-egg-pack/eggs/colorways/0382-blue-pink.png",
	"Divine": "res://client/sprites/pet-egg-pack/eggs/colorways/0188-yellow-silver.png",
	"Eclipsed": "res://client/sprites/pet-egg-pack/eggs/named/0448-ember-peach.png",
	"Wyrmgold": "res://client/sprites/pet-egg-pack/eggs/named/0522-spain.png",
	"Abyssal": "res://client/sprites/pet-egg-pack/eggs/named/0580-void-laser.png",
	"Emberwake": "res://client/sprites/pet-egg-pack/eggs/colorways/0204-orange-gold.png",
	"Hoarfrost": "res://client/sprites/pet-egg-pack/eggs/colorways/0362-cyan-periwinkle.png",
	"Nightbloom": "res://client/sprites/pet-egg-pack/eggs/named/0491-event-horizon.png",
	"Stormglass": "res://client/sprites/pet-egg-pack/eggs/colorways/0350-burgundy-cyan.png",
	"Gravebloom": "res://client/sprites/pet-egg-pack/eggs/colorways/0100-black-lime-green.png",
}


static func sprite_for(variant_name: String) -> String:
	"""The egg sprite for a variant, or "" when there is none (unknown or legacy variant)."""
	if variant_name == "":
		return ""
	var p: String = String(SPRITE_BY_VARIANT.get(variant_name, ""))
	if p == "" or not ResourceLoader.exists(p):
		return ""
	return p
