extends SceneTree
## ⛑ IS A CRAFTED ITEM WORTH CRAFTING? Measured against what the game HANDS you at the same level.
##
## Owner 2026-09-17, scoping the crafting reassessment: *"Currently it's a pain to craft and you're
## often making things with no real value or use just to try and level up your crafting skill."*
##
## That is a testable claim, and it is the one fault of the four that does not need a design
## decision first: if a crafted item is competitive with a dropped one, the problem is legibility
## and destination; if it is not, no amount of UI will make crafting worth doing.
##
## ⛑ THE COMPARISON IS AGAINST A REAL DROP, GENERATED BY THE REAL GENERATOR. `equipment_reference`
## records what this codebase gets wrong when it reasons about gear from tables instead: the first
## version of `gearsources` enumerated affix pools and concluded five stats were unobtainable,
## because the class bases are in neither pool. So this CALLS `roll_dungeon_chest_equipment` at the
## recipe's own item level and compares totals, rather than reading a drop table and believing it.
##
## What it reports, per recipe: the crafted item's stat total, the median dropped total at that
## level, and the ratio. A ratio well under 1.0 across the board is the owner's complaint in
## numbers.
##
## Run:
##   godot --headless --path . --script res://tools/probe/crafting_worth.gd

const CD := preload("res://shared/crafting_database.gd")
const DT := preload("res://shared/drop_tables.gd")
const PR := preload("res://shared/power_rank.gd")

## ⛑ MATCHED TO `POWER_CURVE_SAMPLES`. The sizing derives from a 200-sample median; comparing
## it against a 60-sample median measures the difference between two SAMPLES as much as the
## difference between crafted and dropped gear. At 60 this probe reported a per-level spread of
## 0.53x to 1.07x that was mostly its own variance.
##
## Deliberately still an INDEPENDENT sample rather than reading the curve: checking the sizing
## against the number it was built from would be circular and would report 0.80x forever.
const SAMPLES := 200

# ⛑ A CRAFTED ITEM AND A DROPPED ITEM DO NOT STORE THEIR STATS THE SAME WAY, and the first
# run of this probe reported "crafted gear beats drops 52x" because of it. A recipe carries
# `base_stats: {attack: 5, level: 5}`; a drop carries `affixes: {attack_bonus: 29,
# roll_quality: 45, suffix_name: "of Striking"}` and NO `stats` key at all. Summing `stats` on
# a drop gives zero, every drop looks worthless, and the answer comes out backwards - with a
# confident verdict printed underneath it.
#
# Both are additive stat points once the bookkeeping is stripped, so the totals are comparable;
# it is only the CONTAINER that differs.
const NOT_POWER := ["level", "value", "durability", "weight",
	"roll_quality", "prefix_name", "suffix_name", "created_at", "id"]


func _stat_total(stats: Dictionary) -> float:
	var t := 0.0
	for k in stats.keys():
		if String(k) in NOT_POWER:
			continue
		var v = stats[k]
		if v is int or v is float:
			t += float(v)
	return t


func _init() -> void:
	var dt = DT.new()
	get_root().add_child(dt)
	seed(1234)

	# Bucket recipes by item level so one drop sample serves every recipe at that level.
	var by_level: Dictionary = {}
	var equip_n := 0
	for rid in CD.RECIPES:
		var r: Dictionary = CD.RECIPES[rid]
		var ot := String(r.get("output_type", ""))
		if not (ot in ["weapon", "armor"]):
			continue
		var bs: Dictionary = r.get("base_stats", {}) if r.get("base_stats", null) is Dictionary else {}
		var lvl: int = int(bs.get("level", 0))
		if lvl <= 0:
			continue
		equip_n += 1
		if not by_level.has(lvl):
			by_level[lvl] = []
		# ⛑ THE SIZED STATS, THE SAME CALL THE SERVER MAKES. Reading the authored `base_stats`
		# here would measure the recipe TABLE rather than what a player receives, and would
		# keep reporting the pre-fix number forever while the game was fixed - the exact
		# shape of instrument defect this arc has already hit twice.
		var sized: Dictionary = CD.curve_sized_base_stats(r, dt)
		by_level[lvl].append({"id": String(rid), "name": String(r.get("name", rid)),
			"total": _stat_total(sized), "skill": int(r.get("skill_required", 0)),
			"slot": String(r.get("output_slot", "?"))})

	print("equipment recipes with a level: %d, across %d distinct item levels" % [equip_n, by_level.size()])
	print("")
	print("%-6s %-26s %8s %10s %8s" % ["lvl", "crafted item", "crafted", "drop med", "ratio"])

	var levels: Array = by_level.keys()
	levels.sort()
	var ratios: Array = []
	var by_slot: Dictionary = {}
	var by_lvl_ratio: Dictionary = {}
	var worse := 0
	var better := 0
	for lvl in levels:
		# One drop sample for this level, from the REAL generator.
		var tier: int = int(PR.grade_for_level(int(lvl)).get("tier", 1))
		var drops: Array = []
		for i in range(SAMPLES):
			var it: Dictionary = dt.roll_dungeon_chest_equipment(tier, int(lvl))
			if it.is_empty():
				continue
			# `affixes` is where a dropped item keeps its stats. See NOT_POWER above.
			var st: Dictionary = it.get("affixes", {}) if it.get("affixes", null) is Dictionary else {}
			if st.is_empty():
				continue
			drops.append(_stat_total(st))
		if drops.size() < SAMPLES / 4:
			# ⛑ REPORTED, NOT QUIETLY SKIPPED. If the generator will not produce gear at a level,
			# that is itself a finding about that level - and comparing against two samples
			# would produce a ratio that looks like a measurement and is not one.
			print("%-6d  ** only %d of %d rolls produced equipment - not compared **" % [
				int(lvl), drops.size(), SAMPLES])
			continue
		drops.sort()
		var med: float = float(drops[drops.size() / 2])
		for rec in by_level[lvl]:
			var ratio: float = float(rec["total"]) / maxf(1.0, med)
			ratios.append(ratio)
			var sl := String(rec["slot"])
			if not by_slot.has(sl):
				by_slot[sl] = []
			by_slot[sl].append(ratio)
			if not by_lvl_ratio.has(lvl):
				by_lvl_ratio[lvl] = []
			by_lvl_ratio[lvl].append(ratio)
			if ratio < 0.8:
				worse += 1
			elif ratio > 1.25:
				better += 1
			print("%-6d %-26s %8.0f %10.0f %7.2fx" % [
				int(lvl), String(rec["name"]).substr(0, 26), float(rec["total"]), med, ratio])

	ratios.sort()
	print("")
	print("===== FAULT ONE: IT IS PER-SLOT, NOT ACROSS THE BOARD =====")
	# ⛑ The averages hide this completely. Armour and amulets are competitive; weapons,
	# shields, boots and rings are nowhere near. A single "crafting is weak" number would send
	# someone to buff all of it and overshoot the half that is already fine.
	var slots: Array = by_slot.keys()
	slots.sort()
	for sl in slots:
		var rs: Array = by_slot[sl]
		rs.sort()
		print("  %-10s n=%-3d median %.2fx   (worst %.2fx, best %.2fx)" % [
			String(sl), rs.size(), float(rs[rs.size() / 2]), float(rs[0]), float(rs[rs.size() - 1])])

	print("")
	print("===== FAULT TWO: THE LEVEL CURVE IS ERRATIC, NOT MERELY LOW =====")
	# ⛑ THE FIRST LABEL ON THIS SECTION SAID "IT DECAYS WITH LEVEL" AND THE DATA DOES NOT SAY
	# THAT. Measured: 0.31x at level 5, 0.52 at 15, 0.46 at 30, 0.26 at 50, 0.72 at 70, 1.01 at
	# 80, 1.38 at 90 - and then 0.27 at 100 and 0.17 at 150. That is not a decay, it is noise:
	# a band where crafting is genuinely good sits between two where it collapses.
	#
	# The distinction changes the fix. A decay is corrected with a scaling term; THIS needs the
	# recipe stats derived from the same level curve the drops use, because they are hand-authored
	# constants and the drops are generated - so the two can only ever agree by coincidence, and
	# at level 90 they happen to and at level 100 they happen not to.
	var lv2: Array = by_lvl_ratio.keys()
	lv2.sort()
	for lv in lv2:
		var rr: Array = by_lvl_ratio[lv]
		rr.sort()
		print("  item level %-4d median %.2fx across %d recipes" % [
			int(lv), float(rr[rr.size() / 2]), rr.size()])

	print("")
	print("===== THE ANSWER =====")
	if ratios.is_empty():
		print("  no comparable recipes - the measurement did not run")
		quit(1)
		return
	var med_ratio: float = float(ratios[ratios.size() / 2])
	print("  %d craftable weapons/armour compared against real drops at their own level" % ratios.size())
	print("  median ratio %.2fx   |   worse than 0.80x: %d   better than 1.25x: %d" % [
		med_ratio, worse, better])
	print("  p10 %.2fx   p90 %.2fx" % [
		float(ratios[int(ratios.size() * 0.1)]), float(ratios[int(ratios.size() * 0.9)])])
	print("")
	if med_ratio < 0.8:
		print("  VERDICT: the owner is right - the median crafted item is WORSE than what the")
		print("  game hands you for free at the same level. Legibility cannot fix that.")
	elif med_ratio > 1.25:
		print("  VERDICT: crafted gear BEATS drops - so the complaint is destination and")
		print("  legibility, not power, and the fix is UI and material sinks.")
	else:
		print("  VERDICT: crafted and dropped gear are comparable. The complaint is then about")
		print("  EFFORT and CLARITY rather than output power - a different fix.")
	quit()
