## GENERATED by tools/bake_overworld_tiles.py - DO NOT HAND-EDIT.
##
## How many cells each tile's full-size art covers, as [rows, cols]. The renderer anchors
## the art to the BOTTOM of its base cell and centres it horizontally, so a span of R rows
## reaches R-1 cells NORTH and C columns reaches out to either side. `npc_post_database`
## uses this to keep one station art off another station tile, and `overworld_room`
## uses it to decide which tiles get drawn in the big-art pass.
##
## Re-run the baker after changing any span in CUTS; `tools/probe/post_art_does_not_cover_people.gd`
## fails if this file and the layout disagree.

const SPANS := {
	"anvil": [2, 2],
	"apothecary": [3, 2],
	"banner": [2, 2],
	"bench": [1, 2],
	"brazier": [1, 2],
	"companion_stable": [3, 3],
	"door": [2, 2],
	"enchant_table": [2, 2],
	"forge": [3, 2],
	"garden_plot": [2, 2],
	"market": [3, 2],
	"post_marker": [3, 3],
	"quest_board": [3, 3],
	"tent": [2, 2],
	"throne": [2, 1],
	"tower": [3, 1],
	"tree": [3, 2],
	"well": [3, 2],
	"workbench": [2, 2],
	"writing_desk": [2, 2],
}


static func span_for(tile_name: String) -> Vector2i:
	"""Rows and columns of art for a tile, or (1, 1) when it is a plain single cell."""
	var s = SPANS.get(tile_name, null)
	if s == null:
		return Vector2i(1, 1)
	return Vector2i(int(s[0]), int(s[1]))
